export const ShopActionTypes = {
  SET_FULL_ARRAY_OF_PRODUCTS: "SET_FULL_ARRAY_OF_PRODUCTS",
  SET_DISIPLAYED_ARRAY_OF_PRODUCTS: "SET_DISIPLAYED_ARRAY_OF_PRODUCTS",
  SET_VALUE_BY_NAME: "SET_VALUE_BY_NAME",
};
