//Object to declare action types(string type)and make surre to hardly make errors
export const CartActionTypes = {
  SET_VALUE_BY_NAME_CART: "SET_VALUE_BY_NAME_CART",
  INCREASE_VALUE_OF_PRODUCT_BY_ONE: "INCREASE_VALUE_OF_PRODUCT_BY_ONE",
  DECREASE_VALUE_OF_PRODUCT_BY_ONE: "DECREASE_VALUE_OF_PRODUCT_BY_ONE",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  SELECT_ONE_PRODUCT: "SELECT_ONE_PRODUCT",
  SELECT_ALL_OR_DESELECT_ALL: "SELECT_ALL_OR_DESELECT_ALL",
};
